version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    groups:
      submodules:
        patterns:
          - "*"
    schedule:
      interval: "monthly"
      day: "friday"
      time: "06:00"
      timezone: "Europe/Vienna"

  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      github-actions:
        patterns:
          - "*"
    schedule:
      interval: "monthly"
      day: "friday"
      time: "06:00"
      timezone: "Europe/Vienna"
