name: CI
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  change-detection:
    name: 🔍 Change
    uses: cda-tum/mqt-core/.github/workflows/reusable-change-detection.yml@v2.5.0

  cpp-tests:
    name: 🇨‌ Test
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-cpp-tests)
    uses: cda-tum/mqt-core/.github/workflows/reusable-cpp-ci.yml@v2.5.0
    secrets:
      token: ${{ secrets.CODECOV_TOKEN }}
    with:
      setup-z3: true

  code-ql:
    name: 📝 CodeQL
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-code-ql)
    uses: cda-tum/mqt-core/.github/workflows/reusable-code-ql.yml@v2.5.0
    with:
      setup-z3: true
      enable-python: false

  required-checks-pass: # This job does nothing and is only used for branch protection
    name: 🚦 Check
    if: always()
    needs:
      - change-detection
      - cpp-tests
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          allowed-skips: >-
            ${{
              fromJSON(needs.change-detection.outputs.run-cpp-tests)
              && '' || 'cpp-tests,'
            }}
            ${{
              fromJSON(needs.change-detection.outputs.run-code-ql)
              && '' || 'code-ql,'
            }}
          jobs: ${{ toJSON(needs) }}
